# Generated by Django 2.1.2 on 2018-11-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Document')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.User')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='id_user_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.User_Document'),
        ),
    ]
