# Generated by Django 2.1.2 on 2018-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='act',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
