# Generated by Django 2.1.2 on 2018-11-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_auto_20181104_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.Document'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
