# Generated by Django 2.1.2 on 2018-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
