# Generated by Django 2.1.2 on 2018-11-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0012_auto_20181108_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.Document'),
        ),
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.Project'),
        ),
    ]
