# Generated by Django 2.1.2 on 2018-11-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_auto_20181108_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_key',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='secret_key',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
