# Generated by Django 2.1.2 on 2018-11-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_auto_20181109_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='document',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='document',
            name='private_key_path',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='public_key_path',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
