# Generated by Django 2.1.2 on 2018-11-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_auto_20181109_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
