# Generated by Django 2.1.2 on 2018-11-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0016_auto_20181109_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='private_key_path',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='public_key_path',
            field=models.BinaryField(null=True),
        ),
    ]
