# Generated by Django 2.1.2 on 2018-11-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_auto_20181109_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='private_key_path',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='public_key_path',
            new_name='public_key',
        ),
    ]
