# Generated by Django 2.1.2 on 2018-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_auto_20181109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='private_key',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='public_key',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
