# Generated by Django 2.1.2 on 2018-11-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0022_auto_20181113_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.Document'),
        ),
    ]
