# Generated by Django 2.1.2 on 2018-11-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0023_auto_20181113_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='signature2',
            field=models.BinaryField(max_length=1000, null=True),
        ),
    ]
