# Generated by Django 2.1.2 on 2018-11-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0024_sign_signature2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='signature2',
        ),
    ]
