# Generated by Django 2.1.2 on 2018-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0025_remove_sign_signature2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
