# Generated by Django 2.1.2 on 2018-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0027_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
