# Generated by Django 2.1.2 on 2018-11-17 17:27

from django.db import migrations, models
import dms.models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0032_auto_20181117_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=dms.models.user_directory_path),
        ),
    ]
