# Generated by Django 2.1.2 on 2018-11-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0036_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
