# Generated by Django 2.1.2 on 2018-11-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0037_commentary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.Document'),
        ),
    ]
