# Generated by Django 2.1.2 on 2018-11-18 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0039_auto_20181118_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=1500)),
                ('dueDate', models.DateField(null=True)),
                ('createDate', models.DateField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('menRespons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menRespons', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.Project')),
                ('taskGiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskGiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
