# Generated by Django 2.1.2 on 2018-11-22 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0040_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='admin_users', to='dms.Document'),
        ),
    ]
